
const Data = [
    {
      id: 1,
      img: "https://m.media-amazon.com/images/I/6125yAfsJKL.AC_UX575.jpg",
      title: "Nike Air Monarch IV",
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Nike",
      color: "white",
      category: "sneakers",
    },
    {
      id: 2,
      img: "https://m.media-amazon.com/images/I/519MRhRKGFL.AC_UX575.jpg",
      title: "Nike Air Vapormax Plus",
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Nike",
      color: "red",
      category: "sneakers",
    },
  
    {
      id: 3,
      img: "https://m.media-amazon.com/images/I/51+P9uAvb1L.AC_UY695.jpg",
      title: "Nike One Sneaker",
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Nike",
      color: "green",
      category: "sneakers",
    },
    {
      id: 4,
      img: "https://m.media-amazon.com/images/I/71oEKkghg-L.AC_UX575.jpg",
      title: "Adidas Running Shoe",
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Adidas",
      color: "black",
      category: "sneakers",
    },
    {
      id: 5,
      img: "https://m.media-amazon.com/images/I/41M54ztS6IL.AC_SY625._SX._UX._SY._UY.jpg",
      title: "Flat Slip Pumps",
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Vans",
      color: "green",
      category: "flats",
    },
  ];
  export default Data;